apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9teURhdGFiYXNl
  SESSION_SECRET: MTIzNA==
  PORT: MzEzMA==
  EMAIL_USER: cmFnaHVkaGFyMTA4QGdtYWlsLmNvbQ==
  EMAIL_PASS: UmFnaHVAMTQz
  MONGO_INITDB_DATABASE: bXlEYXRhYmFzZQ==
