apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        ports:
        - containerPort: 3130  # Ensure this matches the app's exposed port
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: MONGODB_URI
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: EMAIL_USER
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: EMAIL_PASS
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: PORT
